import type { LobbyCategory } from '@/types/lobby'

export const LOBBY_CATEGORIES: LobbyCategory[] = [
  {
    id: 'cat-marketing',
    name: 'Marketing Intelligence',
    slug: 'marketing',
    description: 'Practical marketing, growth intelligence, conversion funnels, and customer acquisition mechanics.',
    displayOrder: 1,
    isActive: true,
    seoTitle: 'Marketing Intelligence — The Lobby | Avorria',
    seoDescription: 'Empirical marketing intelligence and growth mechanics for modern business leaders.',
  },
  {
    id: 'cat-google-search',
    name: 'Google & Search',
    slug: 'google-search',
    description: 'Google core updates, search engine intelligence, technical SEO, indexation mechanics, and local search developments.',
    displayOrder: 2,
    isActive: true,
    seoTitle: 'Google & Search Engine Intelligence — The Lobby | Avorria',
    seoDescription: 'Empirical analysis of Google algorithm updates, crawl dynamics, and technical search architecture.',
  },
  {
    id: 'cat-meta-social',
    name: 'Meta & Social Platforms',
    slug: 'meta-social',
    description: 'Meta, Facebook, Instagram, algorithmic auction mechanics, ad infrastructure, and attribution dynamics.',
    displayOrder: 3,
    isActive: true,
    seoTitle: 'Meta & Social Platform Shifts — The Lobby | Avorria',
    seoDescription: 'Deconstructing paid social machine-learning changes, creative infrastructure, and attribution.',
  },
  {
    id: 'cat-websites',
    name: 'Websites & UX',
    slug: 'websites',
    description: 'Website strategy, UX architecture, interaction latency (INP), conversion design, and modern front-end technology.',
    displayOrder: 4,
    isActive: true,
    seoTitle: 'Website Architecture & UX Intelligence — The Lobby | Avorria',
    seoDescription: 'Technical telemetry covering interaction latency, Core Web Vitals, and sovereign web engineering.',
  },
  {
    id: 'cat-small-business',
    name: 'Small Business Guidance',
    slug: 'small-business',
    description: 'Practical, high-leverage commercial guidance, vendor evaluation, contract structures, and risk mitigation for growing firms.',
    displayOrder: 5,
    isActive: true,
    seoTitle: 'Small Business Digital Guidance — The Lobby | Avorria',
    seoDescription: 'Practical digital decision-making frameworks and commercial protection for business owners.',
  },
  {
    id: 'cat-technology',
    name: 'Applied Technology & AI',
    slug: 'technology',
    description: 'Useful developments across digital infrastructure, deterministic AI pipelines, automation, and software sovereignty.',
    displayOrder: 6,
    isActive: true,
    seoTitle: 'Applied Technology & AI Systems — The Lobby | Avorria',
    seoDescription: 'Deterministic AI agents, cloud architectures, and sovereign digital infrastructure.',
  },
  {
    id: 'cat-avorria',
    name: 'Avorria Dispatches',
    slug: 'avorria',
    description: 'Avorria announcements, engineering releases, studio milestones, and selected forensic case studies.',
    displayOrder: 7,
    isActive: true,
    seoTitle: 'Studio Dispatches & Benchmarks — The Lobby | Avorria',
    seoDescription: 'Engineering logs, open benchmarks, and announcements from the Avorria workshop.',
  },
  // Supporting editorial taxonomies for existing dossiers
  {
    id: 'cat-teardowns',
    name: 'Forensic Teardowns',
    slug: 'teardowns',
    description: 'Objective, observable dissections of why high-budget corporate digital platforms break down in production.',
    displayOrder: 8,
    isActive: true,
    seoTitle: 'Forensic Digital Teardowns — The Lobby | Avorria',
    seoDescription: 'Observable architectural dissections of production website failures.',
  },
  {
    id: 'cat-digital-strategy',
    name: 'Digital Strategy',
    slug: 'digital-strategy',
    description: 'Studio economics, fixed-scope engineering sprints versus cost-plus time-and-materials, and software sovereignty.',
    displayOrder: 9,
    isActive: true,
    seoTitle: 'Digital Strategy & Economics — The Lobby | Avorria',
    seoDescription: 'Fixed-scope commercial models versus agency retainers for scaling enterprises.',
  },
  {
    id: 'cat-search-engine-intelligence',
    name: 'Search Engine Intelligence',
    slug: 'search-engine-intelligence',
    description: 'Empirical analysis of Google algorithm updates, crawl dynamics, and technical search architecture.',
    displayOrder: 10,
    isActive: true,
    seoTitle: 'Search Engine Intelligence — The Lobby | Avorria',
    seoDescription: 'Deep technical audits, rendering telemetry, and crawl budget engineering.',
  },
  {
    id: 'cat-platform-shifts',
    name: 'Platform Shifts',
    slug: 'platform-shifts',
    description: 'Algorithmic shifts across ad networks, machine-learning attribution, and digital distribution.',
    displayOrder: 11,
    isActive: true,
    seoTitle: 'Platform Shifts & Algorithmic Auctions — The Lobby | Avorria',
    seoDescription: 'Deconstructing platform updates, ad auctions, and programmatic conversion telemetry.',
  },
  {
    id: 'cat-applied-ai',
    name: 'Applied AI',
    slug: 'applied-ai',
    description: 'Deterministic AI agents, structured JSON schema validations, and enterprise workflow automation.',
    displayOrder: 12,
    isActive: true,
    seoTitle: 'Applied AI & Autonomous Systems — The Lobby | Avorria',
    seoDescription: 'Building enterprise AI systems without hallucination using deterministic state machines.',
  },
  {
    id: 'cat-website-intelligence',
    name: 'Website Intelligence',
    slug: 'website-intelligence',
    description: 'Technical audits comparing monolithic CMS plugin debt against sovereign modern web stacks.',
    displayOrder: 13,
    isActive: true,
    seoTitle: 'Website Intelligence & Architectural Audits — The Lobby | Avorria',
    seoDescription: 'Forensic audits of CMS bloat, security debt, and sub-second edge rendering.',
  },
]

export function getCategoryBySlug(slug: string): LobbyCategory | undefined {
  return LOBBY_CATEGORIES.find((c) => c.slug === slug && c.isActive)
}

export function getAllCategories(): LobbyCategory[] {
  return LOBBY_CATEGORIES.filter((c) => c.isActive).sort((a, b) => a.displayOrder - b.displayOrder)
}
