/**
 * Avorria — The Lobby: Editorial Content & Strategic Teardowns
 *
 * Thought leadership, architectural critiques, and commercial essays.
 * Replaces generic agency blogs with high-value technical journalism.
 */

export interface LobbyArticle {
  slug: string
  title: string
  sequence: string
  category: 'Critique' | 'Architecture' | 'Commercial Strategy' | 'Teardown'
  publishedDate: string
  readTime: string
  synopsis: string
  contentMarkdown: string
}

export const LOBBY_ARTICLES: LobbyArticle[] = [
  {
    slug: 'websites-we-would-fire',
    title: 'Websites We Would Fire: Five Digital Failure Archetypes',
    sequence: '01',
    category: 'Critique',
    publishedDate: '2025-02-15',
    readTime: '6 min read',
    synopsis:
      'Most underperforming corporate websites suffer from the same five structural defects. An architectural teardown of why award-winning designs frequently fail to generate commercial pipeline.',
    contentMarkdown: `
### The Illusion of Digital Presence

Every year, millions of pounds are wasted on web redesigns that look immaculate in presentation decks but fail completely in production. When a digital flagship fails to produce commercial pipeline, leadership often blames the marketing channels or the sales team. In reality, the flaw is almost always architectural.

Below are the five distinct failure archetypes we consistently encounter when diagnosing stalled enterprise platforms.

---

#### 1. The 'Hero Slider From 2012'
**The Symptom:** A massive carousel on the homepage rotating through four disconnected marketing messages.
**The Reality:** User research has proven for over a decade that fewer than 1% of visitors ever click past the first slide. Carousels destroy Largest Contentful Paint (LCP), confuse search crawlers, and indicate an internal committee that could not agree on what the company actually does.
**The Fix:** A single, authoritative typographic headline, uncompromising value proposition, and an immediate visual anchor.

---

#### 2. The 'Do Everything For Everyone' Agency Maze
**The Symptom:** A navigation menu featuring forty dropdown links offering everything from TikTok management to custom enterprise cloud infrastructure.
**The Reality:** Generalism kills pricing power. High-value enterprise buyers do not hire generalist shops; they hire specialist engineering firms with deep discipline competence.
**The Fix:** Ruthless taxonomy reduction. Group capabilities into three rigorous technical pillars: Build, Search, and Systems.

---

#### 3. The 'No Clear Action' Portfolio
**The Symptom:** Aesthetic imagery and abstract taglines without a single obvious commercial next step.
**The Reality:** The site treats visitors like museum patrons rather than commercial prospects.
**The Fix:** Clear, qualified pathways: a direct scoping intake, an executive briefing, or a technical architecture review.

---

#### 4. The 'Wall of Text, Zero Proof' Brochure
**The Symptom:** Endless paragraphs of corporate jargon ("synergy", "cutting-edge", "game-changing") unsupported by verifiable technical specifications or real deliverables.
**The Reality:** Sophisticated buyers look for specifics: technology stacks, delivery timelines, integration constraints, and architectural proof.
**The Fix:** Replace adjectives with schematics, factual case studies, and engineering ledgers.

---

#### 5. The 'Beautiful But Useless' Award-Bait Demo
**The Symptom:** Heavy 3D canvases, custom cursors that lag, sound effects, and five-second preloader screens that alienate mobile visitors and tank Core Web Vitals.
**The Reality:** When interface motion exists for the designer's portfolio rather than the customer's comprehension, conversion rates plummet.
**The Fix:** Restrained motion. Subordinate animation to content. Use WebGL only where a genuine 3D model creates direct comprehension.
    `,
  },
  {
    slug: 'the-agency-retainer-trap',
    title: 'The Agency Retainer Trap: Why 40-Page PDFs Replace Progress',
    sequence: '02',
    category: 'Teardown',
    publishedDate: '2025-01-20',
    readTime: '5 min read',
    synopsis:
      'How the traditional digital marketing agency model incentivizes task inflation, vanity metrics, and perpetual "optimization" without shipping production code.',
    contentMarkdown: `
### Activity is Not Achievement

If your company pays £4,000 to £10,000 every month for digital marketing, review your latest monthly report.

Chances are it is a 30 to 50 page slide deck or PDF generated by automated reporting software. It is full of charts depicting impressions, clicks, keyword rankings for brand terms, and vague summaries such as *"ongoing monthly optimization and backlink monitoring"*.

Now ask a simple question: **What was actually built, fixed, or shipped last month?**

In most agencies, the answer is remarkably close to nothing.

---

#### The Mechanics of Retainer Drift

The traditional agency model is fundamentally misaligned with client growth:
1. **The Junior Shift:** You were pitched by senior partners, but your account is maintained by entry-level coordinators juggling twenty clients simultaneously.
2. **The Optimization Defense:** "Optimizing" is the perfect non-falsifiable agency activity. It requires no code commits, no schema deploys, and no structural accountability.
3. **Vanity Reporting:** When organic revenue is flat, agencies highlight impressions. When impressions are flat, they highlight click-through rates. The metric changes to whatever looks green.

---

#### The Engineering Alternative

At Avorria, we approach digital growth through an engineering lens:
- **Tracking First:** We do not touch creative or spend capital until server-side tracking and attribution are mathematically sound.
- **Production Code:** Real progress is reflected in git commits, deployed Next.js routes, cleaned crawl hierarchies, and automated workflows.
- **Blunt Teardowns:** If a campaign or channel fails, we state it immediately and reallocate capital.

When you purchase digital capability, demand code and commercial pipeline—not slide decks.
    `,
  },
]

export function getLobbyArticles(): LobbyArticle[] {
  return LOBBY_ARTICLES
}

export function getLobbyArticleBySlug(slug: string): LobbyArticle | undefined {
  return LOBBY_ARTICLES.find((a) => a.slug === slug)
}
