export { CinematicPlate } from './CinematicPlate'
export type { CinematicPlateProps, AspectRatio, FadeTone } from './CinematicPlate'
export { EditorialChapter } from './EditorialChapter'
export type { EditorialChapterProps, ChapterTheme } from './EditorialChapter'
export { ParallaxPlate } from './ParallaxPlate'
export type { ParallaxPlateProps } from './ParallaxPlate'
export { ImageReveal } from './ImageReveal'
export type { ImageRevealProps, RevealDirection } from './ImageReveal'
export { LargeNumber } from './LargeNumber'
export type { LargeNumberProps } from './LargeNumber'
export { SectionLabel } from './SectionLabel'
export type { SectionLabelProps } from './SectionLabel'
export { AnimatedLink } from './AnimatedLink'
export type { AnimatedLinkProps } from './AnimatedLink'

